version: '3'

services:

  catalog-database:
    image: postgres:14.9-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    container_name: 'catalog_database'
    restart: always
    volumes:
      - ./init-db-postgres:/docker-entrypoint-initdb.d/:ro
    ports:
      - '0.0.0.0:5432:5432/tcp'

  catalog-backend:
    container_name: catalog_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: catalog-database
    links:
      - catalog-database

  catalog-frontend:
    container_name: catalog_frontend
    restart: always
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - catalog-backend
